### ISSUE TITLE
Lando local example

### ISSUE THREAD

**Issue by woodseowl** [CU-CommunityApps/CD-LaravelStarterKit#40]
In order to have someone be able to build and test using Lando, they need to do some local configuration. A `.lando.example.local.yml` would be a good place to put this. This file would be in `/project` to indicate that it goes in the Laravel project being created and it is only for development testing (could be commented, could be not installed, could be optionally installed).

Also, the `CONTRIBUTING.md` file has an example `.lando.local.yml` file, but it needs to not have the base `.lando.yml` content. This could all be replaced with a reference to the `.lando.example.local.yml` file.

**Comment by woodseowl** [comment]
In #38 I updated the `CONTRIBUTING.md` instructions for local development composer configuration, moving the `.lando.local.yml` content into an example file, [lando.local.dev.yml](https://github.com/CU-CommunityApps/CD-LaravelStarterKit/pull/38/files#diff-5c9b98bb1158c4200fbbd68b78373b7d66576774ab981bc5a5d83d17ece8c44f).

This isn't exactly what any of us described in the Jan. 10 meeting, but I think it meets the intent?

@inaydich Are you good with this solution? Mostly I just want the instructions to be clear and unfortunately this is a very nuanced use of Lando and Composer.

**Comment by inaydich** [comment]
> @inaydich Are you good with this solution? Mostly I just want the instructions to be clear and unfortunately this is a very nuanced use of Lando and Composer.

yes, that looks good. Thanks.
